rm(list=ls())
library(ISLR)
library(boot)
data(Default)
summary(Default)
boxplot(Default$balance)
g1<-glm(default~balance+income,family=binomial,data=Default)
summary(g1)
g2<-glm(default~scale(balance)+scale(income),family=binomial,data=Default)
summary(g2)
err<-numeric(3)
set.seed(630829)
index<-sample(1:nrow(Default),size=8000,replace = F)
g3<-glm(default~balance+income+student,family=binomial,data=Default[index,])
pred1<-predict(g3,type="response",newdata=Default[-index,])
pred2<-ifelse(pred1>0.5,"Yes","No")
cm1<-prop.table(xtabs(~pred2+Default$default[-index]),2)
err[3]<-mean(as.numeric(pred2!=Default$default[-index]))
#### Ex 6 starts ########
g1<-glm(default~balance+income,family=binomial,data=Default)
summary(g1)
boot.fn<-function(data,index){
return(coef(glm(default~balance+income,family=binomial,data=data,subset=index)))  
}
b1<-boot(data=Default,statistic=boot.fn,R=1000)
summary(b1)
